[package]
name = "pfnatd"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.1"

[dependencies]
anyhow = "1.0.100"
ctrlc = "3.5.0"
env_logger = "0.11.8"
libc = { version = "0.2.177", features = ["extra_traits"] }
log = "0.4.28"
